apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: default-bitnami
  project: defaultproject
spec:
  endpoint: https://charts.bitnami.com/bitnami
  options: {}
  type: Helm
status:
  projects:
  - projectId: d2wpz6k
    repositoryId: kgxn08m
  webhookConfig:
    webhookSecret: aefefd2e5bd83b96cb206bf84aadc09b59a72442835c119b2cded28d37bed371
    webhookURL: https://console.rafay.dev/v2/config/webhook/repository/kgxn08m
