apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: workloadrepo11
  project: defaultproject
spec:
  agents:
  - name: eksagent
  credentials:
    password: sealed://credentials.password
    username: samanthapuri
  endpoint: https://github.com/Samanthapuri/workloadrepo11.git
  options: {}
  secret:
    name: file://artifacts/workloadrepo11/sealed-secret.yaml
  type: Git
status:
  agents:
  - id: 3mx5q72
    name: eksagent
  projects:
  - projectId: d2wpz6k
    repositoryId: k5lz7w2
  webhookConfig:
    webhookSecret: 5e3bf5a7e489c76b4cbbcf6fc9a695377d8c19320f9ad9baa144f2999903fab4
    webhookURL: https://console.rafay.dev/v2/config/webhook/repository/k5lz7w2
