apiVersion: security.k8smgmt.io/v3
kind: ClusterNetworkPolicyRule
metadata:
  name: test1
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/test1/cilium_clusterwide.yaml
    options: {}
    type: Yaml
  version: v1
