apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workloadrepo12
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCuRCHfi57MuzrgNScTfnA5pyiK7EYrz4jtBErjtiDYzRCUPgz3qWmucpwQOYxEYAUCC64EMQqVosYkXR6MU50uL3MBYuQ8UA1VLHSm4T9/WkmnWtSMzRWm2o6RDoBwdIs8cW/wl6JTSf0tcNj9xC4GYnAaQryJ0BwyYoeyUZg4Ckugn87+iGjRAAqvWPtjKFSxEmnO+01raWde1NxTn4VpMS0ck8ZobbiACh7cYsVLDBKh2avowp0t2odB/4saYD/GqM7rWwBsknOJ7FZV8MqoMBNq8u0YcM+TwQACjb0MqLA0pBUsxk16j3vO7j5REIMPeQy1EbIO6wEyf5xJvxO/c6D7nISoyfT7LthiEB51vLRJ3n4dHCAyXwOSfwQXQo1jFt1bfC6XSKyqgvJNT4rt/bW9/kY26Io=
  template:
    metadata:
      creationTimestamp: null
      name: workloadrepo12
      namespace: default

