global:
  Rafay:
    ClusterLabels: {}

connector:
  image:
    repository: registry.rafay-edge.net/rafay/rafay-connector
    pullPolicy: IfNotPresent
    tag: r1.24.0-2

controller:
  image:
    repository: registry.rafay-edge.net/rafay/cluster-controller
    pullPolicy: IfNotPresent
    tag: r1.24.0-2

relay:
  image:
    repository: registry.rafay-edge.net/rafay/rafay-relay
    pullPolicy: IfNotPresent
    tag: r1.24.0-2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

initContainer:
  image:
    repository: registry.rafay-edge.net/rafay/busybox
    pullPolicy: IfNotPresent
    tag: 1.33

token: ""
api_addr: api.rafay.dev.
control_addr: control.rafay.dev.
allow_insecure_bootstrap: ""
cluster_id: ""
max_dials: "2"
relays: ""
http_proxy: ""
https_proxy: ""
no_proxy: ""
proxy_auth: ""
openshift: false
