apiVersion: apps.k8smgmt.io/v3
kind: WorkloadTemplate
metadata:
  name: bluedeployment
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: green/
      repository: myrepo
      revision: master
      valuesPaths:
      - name: green/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
