apiVersion: opa.k8smgmt.io/v3
kind: OPAProfile
metadata:
  name: "314"
  project: defaultproject
spec:
  installationParams:
    auditInterval: 60
    constraintViolationsLimit: 20
  opaVersion: 3.16.3
  version: v1
