configmap:
  test: |-
    #!/bin/bash

    if [ -z $1 ] || [ -z $2 ] || [ -z $3 ] || [ -z $4 ] || [ -z $5 ] || [ -z $6 ]
    then
    echo "Arguments expected secret_file_location vault_role vault_url"
    echo "ex: retrieveVaultSecrets.sh hostname  appSecrets role awsaccount clusterid appsecretPath reset debug"
    exit
    fi

    vhostname=$1
    vappsecrets=$2
    vrole=$3
    vawsaccount=$4
    vclusterid=$5
    vappsecretpath=$6
    vdebug=$7
    vreset=$8

    if [ -z "$vappsecretpath" ]
    then
    loc_write='/etc/app/'
    else
    loc_write=$vappsecretpath
    fi


    if [ -z "$vreset" ]
    then
    reset="n"
    else
    reset="y"
    fi


    KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);
    curl -k --request POST --data '{"jwt": "'"$KUBE_TOKEN"'", "role": "'"$vrole"'" }' "https://$vhostname/v1/auth/$vawsaccount/$vclusterid/login"  | jq -j '.auth.client_token' > /etc/vault/token;
    X_VAULT_TOKEN=$(cat /etc/vault/token);
