apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: fmtest
  project: defaultproject
spec:
  agents:
  - name: nutanix
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
  repositoryOptions:
    branch: main
    directoryPath: test
    name: nutanix-repo
  version: v1
  versionState: active
