apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tfdemo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQDDZYvYwO+rzrWrN3zwzOOirhhDyRmGOdvF2VtcBCtU1MuAgXXEjA/L9VObLFPjdqDr1OaM8J+g2swMKtiL/NFozkKb94DYxn+2BqiJRqoa4EzQi5jd8nxq47qfroJMEh4hf1+vDlp23/+rTt88F9UPt5BZHsZSK5FuHikjWfMhqlWN2/4EXyJR+tn+Ez+9sS/o9fVUmpKhmgmZM/IpyIBFJBUPCEdIWbUt2ueM78xOZWdTsEgHH4bY/+8iGSuMc/uM1iCyfdt1tX+hRcXEhDqpdNNxWwZQ+bisloQuuDs2/IiBcduqi72FiOJklU6tNRkJy4t9I7WrShYmUNDYsiKhXSCG0nhdmhZxsawRPmuDf/eqXLATJOIt2BqtJpwqcHnWPhc+4r9aYJEwXRHq3oGFKEvUvm/zbO0=
  template:
    metadata:
      creationTimestamp: null
      name: tfdemo
      namespace: default

