apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: testsync
  project: defaultproject
spec:
  active: true
  stages:
  - config:
      destinationRepo:
        path:
          name: "18042025"
        repository: workloadrepo2
        revision: main
      includedResources:
      - name: '*'
      systemToGitSync: true
    name: syssync
    type: SystemSync
