apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workloadrepo9
  namespace: default
spec:
  encryptedData:
    credentials.password: AQDS2xIGWE4cNjtZ2xYWlzJdw79vIGaAmJ8++KY9l1rcGpCkEPINGYOgM9f5byZO2XyopHNz53aUCb8Bzzn01fJ5mQiwGxZ3HfiwGc2WuscZ6K0FaA9w7LXlSc4Vb449zGlP/M3t6Q4TTJiVNAUbV+Op8KPawj/HvPtzCNQn2E3FfPXSvMAFb6j1hGCcpltyhgHnTZuiS9Cg09EthdqNjH4tplWqZC/o3jfaZ6MN3NnlRdFjV21TQsjmo0OQCQW6YJH6ipXz3o9yxE/0Fvwxep+74l95xsSbPB5iA223JvGVBAWVbR2HanoSeil4S+HUeZ0bCnrIKgSiy0O+Zc9NkM/pbFwLus1FI+glqt4fvzoXH5nOJejX8etg0qjkzh16nqI9uDZ6aKM7gymyUk1v+zne8nGcH6PLEoA=
  template:
    metadata:
      creationTimestamp: null
      name: workloadrepo9
      namespace: default

