apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: nginx
  project: defaultproject
spec:
  artifact:
    artifact:
      catalog: default-helm
      chartName: ingress-nginx
      chartVersion: 4.12.0
      valuesPaths:
      - name: file://artifacts/nginx/relay-values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: testns
  placement:
    selector: rafay.dev/clusterName=vijayseks121220242
  version: nginx-v3-202502032016270000
