apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testwlvijays
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/testwlvijays/testchart-0.1.0.tgz
      valuesPaths:
      - name: file://artifacts/testwlvijays/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: defaultns
  placement:
    environment:
      name: drivertest2
    selector: rafay.dev/clusterName=vijayseks121220242
  version: testwlvijays-v2-202502032219030000
