apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testhelm
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/testhelm/testchart-0.1.0.tgz
      valuesPaths:
      - name: file://artifacts/testhelm/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: defaultns
  placement:
    environment:
      name: drivertest2
    selector: rafay.dev/clusterName=vijayseks121220242
  version: testhelm-v5-202502032122180000
