apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testworkload-4
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://tesapp-0.1.0.tgz
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: default
  placement:
    environment:
      name: fmtest010525
    selector: rafay.dev/clusterName=vijayseks180425
  version: testworkload-4-v2-202505012244280000
