apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testworkload-3
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/testworkload-3/tesapp-0.1.0.tgz
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: defaultns
