apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test1234
  project: defaultproject
spec:
  artifact:
    artifact:
      catalog: rafay-demo-catalog
      chartName: webapp-python
      chartVersion: 1.0.0
      valuesPaths:
      - name: file://artifacts/test1234/values (1).yaml
    options:
      maxHistory: 10
      timeout: 5m0s
      wait: true
    type: Helm
  namespace: default
  placement:
    selector: rafay.dev/clusterName in (vijays03172025,vijayseks121220242)
