apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testworkload-2
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/testworkload-2/tesapp-0.1.0.tgz
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: defaultns
  placement:
    environment:
      name: fmtest010525
    selector: rafay.dev/clusterName=vijayseks180425
  version: testworkload-2-v2-202505011737260000
