apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testcm
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/testcm/testcm.yaml
    type: Yaml
  namespace: defaultns
  placement:
    selector: rafay.dev/clusterName=vijays03172025
  version: testcm-v7-202503261944050000
