apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: workloadrepo34
  project: defaultproject
spec:
  artifact:
    artifact:
      chartName: hello-world
      chartVersion: 0.1.0
      repository: workloadhelmrepo
      valuesRef:
        repository: workloadrepo1
        revision: main
        valuesPaths:
        - name: values/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: workloadrepo34
  placement:
    selector: rafay.dev/clusterName=vijayseks180425
  version: v1
