apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: cost-minimal
  project: defaultproject
spec:
  base:
    name: minimal
    version: 3.2.0
  costProfile:
    name: default-cost-profile-aws
    version: version-1741336869
  defaultAddons:
    enableMonitoring: true
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  type: custom
  version: v1
  versionState: active
