apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: csibp
  project: defaultproject
spec:
  base:
    name: minimal
    version: 2.4.0
  defaultAddons:
    csiSecretStoreConfig:
      providers:
        aws: true
    enableCsiSecretStore: true
  driftWebhook:
    enabled: true
  type: custom
  version: v4
  versionState: active
