apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: custombp
  project: defaultproject
spec:
  base:
    name: minimal
    version: 2.5.0
  customAddons:
  - name: certmanager
    version: v1
  - dependsOn:
    - certmanager
    name: testaddon
    version: v1
  driftWebhook:
    enabled: true
  type: custom
  version: v3
  versionState: active
