apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: custom-bp
  project: defaultproject
spec:
  base:
    name: default
    version: 3.2.0
  componentsCriticality:
  - name: test-configmap
  customAddons:
  - name: test-configmap
    version: v5
  - name: istio-secret
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      gpuOperator: {}
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  type: custom
  version: v6
  versionState: active
