apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: custom-minimal
  project: defaultproject
spec:
  base:
    name: minimal
    version: 2.8.0
  defaultAddons:
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  type: custom
  version: v2
  versionState: active
