apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: custombp1234567
  project: defaultproject
spec:
  base:
    name: default
    version: 2.11.0
  defaultAddons:
    csiSecretStoreConfig:
      providers:
        aws: true
    enableCsiSecretStore: true
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
  versionState: active
