apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: gpu-operator
  project: defaultproject
spec:
  base:
    name: minimal
    version: 3.1.0
  customAddons:
  - name: gpu-operator
    version: 0.0.59
  defaultAddons:
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  type: custom
  version: v5
  versionState: active
