apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: jdevdemo
  project: defaultproject
spec:
  base:
    name: minimal
    version: 3.2.0
  customAddons:
  - name: aws-alb
    version: v2.11-1
  - dependsOn:
    - aws-alb
    name: ingress-nginx
    version: v4
  - dependsOn:
    - ingress-nginx
    name: update-cname
    version: v6
  defaultAddons:
    enableMonitoring: true
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Managed
  type: custom
  version: v11
  versionState: active
