apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: mon
  project: defaultproject
spec:
  base:
    name: minimal
    version: 2.8.0
  defaultAddons:
    enableMonitoring: true
    enableRookCeph: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
  versionState: active
