apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: opaonly
  project: defaultproject
spec:
  base:
    name: default
    version: 2.8.0
  customAddons:
  - name: addfromgit
    version: v3
  defaultAddons:
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  opaPolicy:
    profile:
      name: "314"
      version: v1
  type: custom
  version: v9
  versionState: active
