apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: prombp
  project: defaultproject
spec:
  base:
    name: minimal
    version: 2.10.0
  defaultAddons:
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
  versionState: active
