apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: secretstore
  project: defaultproject
spec:
  base:
    name: default
    version: 2.7.0
  defaultAddons:
    csiSecretStoreConfig:
      enableSecretRotation: true
      providers:
        aws: true
      syncSecrets: true
    enableCsiSecretStore: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
  versionState: active
