apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: testcrds
  project: defaultproject
spec:
  base:
    name: minimal
    version: 3.2.0
  customAddons:
  - name: test-crds
    version: v5
  - dependsOn:
    - test-crds
    name: test-resource
    version: v2
  defaultAddons:
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  type: custom
  version: v5
  versionState: active
