apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: testfmyaml
  project: defaultproject
spec:
  base:
    name: minimal
    version: 3.3.0
  customAddons:
  - name: testyaml
    version: v1
  defaultAddons:
    monitoring:
      gpuOperator: {}
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
  versionState: active
