apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: testbp12346876
  project: defaultproject
spec:
  base:
    name: default
    version: 3.1.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  type: custom
  version: v1
  versionState: active
