apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: testbp
  project: defaultproject
spec:
  base:
    name: default
    version: 2.5.0
  customAddons:
  - name: certmanager
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
  versionState: active
