apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: testvijays
  project: defaultproject
spec:
  base:
    name: prod-gold
    version: v1
  customAddons:
  - name: certmanager
    version: v1
  - dependsOn:
    - certmanager
    name: addon2
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
  versionState: active
