apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: testvaultbp
  project: defaultproject
spec:
  base:
    name: default
    version: 2.7.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  type: custom
  version: v1
  versionState: active
