apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: upstream
  project: defaultproject
spec:
  base:
    name: default-upstream
    version: 2.7.0
  defaultAddons:
    enableRookCeph: true
  driftWebhook:
    enabled: true
  opaPolicy:
    profile:
      name: default
      version: latest
  type: custom
  version: v1
  versionState: active
