apiVersion: v1
data: {}
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: istio-reader-service-account
  name: istio-reader-service-account-istio-remote-secret-token
type: kubernetes.io/service-account-token