apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: argo-rollouts
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: vijayseks15042024
  resourceQuotas: {}
