apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: cert-manager
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: vaulttest
    - key: rafay.dev/clusterName
      value: eks-cluster-vijays-09032023
  resourceQuotas: {}
