apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: dbschematest
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: vijayseks20022024
  resourceQuotas: {}
