apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: default
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: secretstoretestvijays1
    - key: rafay.dev/clusterName
      value: secretstoretest123
  resourceQuotas: {}
