apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: defaultns
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rafay-jdev-lab
    - key: rafay.dev/clusterName
      value: vijays03172025
    - key: rafay.dev/clusterName
      value: vijayseks180425
  resourceQuotas:
    storageRequests: 100Gi
