apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: demo3
  name: demo3
  project: defaultproject
spec:
  drift:
    action: Deny
    enabled: true
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: gkeimporttest
    - key: rafay.dev/clusterName
      value: eks-cluster-vijays-09032023
    - key: rafay.dev/clusterName
      value: vijayseks26122023
  resourceQuotas: {}
