apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  labels:
    keylabel: keyvalue
  name: randomnamespace
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: vijays-eks-test12345
  resourceQuotas: {}
