apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: rctldemons1
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  resourceQuotas: {}
