apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: testns1234
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: openshiftimport
    - key: rafay.dev/clusterName
      value: ubuntumkscluster
  resourceQuotas: {}
