apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: tfdemonamespace
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/projectName
      value: defaultproject
  resourceQuotas: {}
