apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workloadrepo3
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCf+1tGgtwuHPWahQjjoO6Vo7OcsejilnLqEeH/L9W0b3De96AmyPk8drvOAp1ihIgVq+cKykroM8SIHrCfS78MMXE09NwVqKNJMjAxuqX580S1+O16rlEihONhaq8JSUTJK0tdkfqjH+Ip/sNVjUcP+ze5M8FXtlconPcmM2/ccS6y7vv2/haBbTVIaW9EqbWReVqbF1F6XXCVqqeFkynVPfvSZ7Q0HUXdAkuJNpY+GbCflpVg5jLBi4UdG7S7LQXg+Abcbrje8v2I3w5PObk6snVhbpcyZMH+lIV32VZ9MBB19Ir4yC6XNEHcP9kFjsrZUWUNEYIoJpv1lm9JSBcQpQ+Y1zv9QfAyv38VsOR8EubSlbQpVFwovWZzk2PXgEmyNUWVK06yHhLqCcNxqsTEt/EvfDr1xCI=
  template:
    metadata:
      creationTimestamp: null
      name: workloadrepo3
      namespace: default

