apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  annotations:
    rafay.dev/audit_type: BROWSER||Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
      AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
    rafay.dev/audit_user: vijaysamanthapuri@rafay.co
    rafay.dev/audit_user_group: Organization Admins,Organization Read Only
  name: ingress-nginx
  project: defaultproject
spec:
  artifact:
    artifact:
      catalog: default-helm
      chartName: ingress-nginx
      chartVersion: 4.12.0
      valuesPaths:
      - name: file://artifacts/ingress-nginx/values (4).yaml
    type: Helm
  namespace: kube-system
  sharing: {}
  version: v4
  versionState: active
