apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  annotations:
    rafay.dev/audit_type: BROWSER||Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
      AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
    rafay.dev/audit_user: vijaysamanthapuri@rafay.co
    rafay.dev/audit_user_group: Organization Admins,Organization Read Only
  name: karpneter
  project: defaultproject
spec:
  artifact:
    artifact:
      catalog: default-rafay
      chartName: karpenter
      chartVersion: 1.1.2
      valuesPaths:
      - name: file://artifacts/karpneter/values.yaml
    type: Helm
  namespace: defaultns
  sharing: {}
  version: 1.1.2
  versionState: active
