apiVersion: infra.k8smgmt.io/v3
kind: AddonOverride
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: valuesFile
  name: aws-ebs-csi-driver-override
  project: defaultproject
spec:
  placement:
    labels:
    - key: rafay.dev/kubernetesProvider
      value: MKS
  resource:
    selector:
      selector: rafay.dev/system=true,rafay.dev/component=aws-ebs-csi-driver
    type: Addon
  type: Helm
  valuesPath:
    name: file://aws-ebs-csi-driver-override/aws-ebs-csi-driver-override.yaml
