apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: testns
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: testns
subjects:
- kind: ServiceAccount
  name: testsa
  namespace: testns
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testsa
  namespace: testns
---
apiVersion: v1
kind: Secret
metadata:
  name: testsa-secret
  namespace: testns
  annotations:
    kubernetes.io/service-account.name: testsa
type: kubernetes.io/service-account-token
