apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: amrish-env2
  project: defaultproject
spec:
  schedule_optouts:
  - duration: 59m
    name: testschedule1
  template:
    name: amrish-env-template1
    version: ' v2'
    versionState: unspecified
  variables:
  - name: username
    options:
      override:
        type: allowed
      required: true
    value: amrish
    valueType: text
