apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: testct123456
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/testct123456/lb-annotation-check-svc.yaml
    options: {}
    type: Yaml
