apiVersion: integrations.k8smgmt.io/v3
kind: SecretProviderClass
metadata:
  name: testscp
  project: defaultproject
spec:
  artifact:
    artifact: {}
    options: {}
    type: Yaml
  provider: AWS
  sharing: {}
