apiVersion: apps.k8smgmt.io/v3
kind: Override
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: valuesFile
  name: opa-override-customer1
  project: defaultproject
spec:
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: vijayseks121220242
  resource:
    selector:
      name: opa-gatekeeper-3.16.3
    type: Workload
  type: Helm
  valuesPath:
    name: file://opa-override-customer1/opa-override-customer1.yaml
