apiVersion: apps.k8smgmt.io/v3
kind: Override
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: valuesFile
  name: rookceph
  project: defaultproject
spec:
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: cephtest
  resource:
    type: Workload
  type: Helm
  valuesPath:
    name: file://rookceph/rookceph.yaml
