apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: gketest
  project: defaultproject
spec:
  blueprint:
    name: minimal
    version: latest
  cloudCredentials: gcpcreds
  config:
    controlPlaneVersion: "1.29"
    features:
      enableComputeEnginePersistentDiskCSIDriver: true
    gcpProject: on-prem-382813
    location:
      config:
        zone: us-central1-a
      type: zonal
    network:
      access:
        config:
          controlPlaneIPRange: 172.16.0.0/28
          disableSNAT: true
          enableAccessControlPlaneExternalIP: true
          enableAccessControlPlaneGlobal: true
          enablePrivateNodes: true
        type: private
      controlPlaneAuthorizedNetwork:
        authorizedNetwork:
        - cidr: 0.0.0.0/0
          name: test
        enabled: true
      dataPlaneV2: ADVANCED_DATAPATH
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: default
      subnetName: default
    nodePools:
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-4
      name: default-nodepool
      nodeVersion: "1.29"
      size: 3
      upgradeSettings:
        config:
          maxSurge: 1
        strategy: SURGE
  type: gke
