apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: mks-noha-converged-cluster
  project: defaultproject
spec:
  blueprint:
    name: default
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubernetesVersion: v1.30.8
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: vijaysmks24022025
      labels:
        foo: bar
        foo1: bar1
        k8s.fdscloud.io/compute_node: "true"
        k8s.fdscloud.io/edge_node: "true"
        k8s.test.io/key: value
        nvidia.com/cuda.driver-version.full: 560.35.03
        nvidia.com/cuda.driver-version.major: "560"
        nvidia.com/cuda.driver-version.minor: "35"
        nvidia.com/cuda.driver-version.revision: "03"
        nvidia.com/cuda.driver.major: "560"
        nvidia.com/cuda.driver.minor: "35"
        nvidia.com/cuda.driver.rev: "03"
        nvidia.com/cuda.runtime-version.full: "12.6"
        nvidia.com/cuda.runtime-version.major: "12"
        nvidia.com/cuda.runtime-version.minor: "6"
        nvidia.com/cuda.runtime.major: "12"
        nvidia.com/cuda.runtime.minor: "6"
        nvidia.com/gfd.timestamp: "1729623834"
        nvidia.com/gpu: "true"
        nvidia.com/gpu-driver-upgrade-state: upgrade-failed
        nvidia.com/gpu.compute.major: "9"
        nvidia.com/gpu.compute.minor: "0"
        nvidia.com/gpu.count: "8"
        nvidia.com/gpu.deploy.container-toolkit: "true"
        nvidia.com/gpu.deploy.dcgm: "true"
        nvidia.com/gpu.deploy.dcgm-exporter: "true"
        nvidia.com/gpu.deploy.device-plugin: "true"
        nvidia.com/gpu.deploy.driver: pre-installed
        nvidia.com/gpu.deploy.gpu-feature-discovery: "true"
        nvidia.com/gpu.deploy.mig-manager: "true"
        nvidia.com/gpu.deploy.node-status-exporter: "true"
        nvidia.com/gpu.deploy.nvsm: ""
        nvidia.com/gpu.deploy.operator-validator: "true"
        nvidia.com/gpu.family: hopper
        nvidia.com/gpu.machine: PowerEdge-XE9680
        nvidia.com/gpu.memory: "81559"
        nvidia.com/gpu.mode: compute
        nvidia.com/gpu.present: "true"
        nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3
        nvidia.com/gpu.replicas: "1"
        nvidia.com/gpu.sharing-strategy: none
        nvidia.com/mig.capable: "true"
        nvidia.com/mig.config: all-disabled
        nvidia.com/mig.config.state: success
        nvidia.com/mig.strategy: mixed
        nvidia.com/mps.capable: "false"
        nvidia.com/vgpu.present: "false"
        test.kubrnetes.io/region: us-nj
        test.kubrnetes.io/zone: zone1
        test1.kubernetes.io: ""
        test2.kubernetes.io: ""
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.81
      roles:
      - ControlPlane
      - Worker
      ssh:
        ipAddress: 129.146.41.185
    ssh:
      port: "22"
      privateKeyPath: /Users/vijaysamanthapuri/Downloads/controller.key
      username: ubuntu
  type: mks
