apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: mkslabeltest
  project: defaultproject
spec:
  blueprint:
    name: minimal
    version: latest
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubernetesVersion: v1.31.4
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: vijaysmksnode
      labels:
        nvidia.com/gpu.count: "2"
        nvidia.com/gpu.deploy.dcgm-exporter: "true"
        nvidia.com/gpu.deploy.device-plugin: "true"
        nvidia.com/gpu.memory: "11441"
        nvidia.com/gpu.present: "true"
        nvidia.com/gpu.product: Tesla-K80
        nvidia.com/mig.strategy: mixed
        run.ai/fake.gpu: "true"
        run.ai/simulated-gpu-node-pool: default
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.1.221
      roles:
      - ControlPlane
      - Worker
    ssh:
      port: "22"
      privateKeyPath: /root/key
      username: ubuntu
  proxy:
    enabled: true
    httpProxy: http://10.0.0.158:3128
    httpsProxy: http://10.0.0.158:3128
    noProxy: 10.0.0.0/16
  type: mks
