apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: mkstestcluster
  project: defaultproject
spec:
  blueprint:
    name: minimal
  config:
    autoApproveNodes: true
    highAvailability: true
    installerTtl: 365
    kubernetesVersion: v1.29.12
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: vijaysmks02
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.228
      roles:
      - Worker
      - ControlPlane
    - arch: amd64
      hostname: vijaysmks03
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.57
      roles:
      - Worker
      - ControlPlane
    - arch: amd64
      hostname: vijaysmks01
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.76
      roles:
      - Worker
      - ControlPlane
  proxy: {}
  type: mks
