devicePlugin:
  image:
    pullPolicy: Always
    repository: gcr.io/run-ai-staging/fake-gpu-operator/device-plugin
    tag: 0.0.59
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
environment:
  openshift: false
kwokGpuDevicePlugin:
  image:
    pullPolicy: Always
    repository: gcr.io/run-ai-staging/fake-gpu-operator/kwok-gpu-device-plugin
    tag: 0.0.59
  resources:
    limits:
      cpu: 200m
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 200Mi
migFaker:
  image:
    pullPolicy: Always
    repository: gcr.io/run-ai-staging/fake-gpu-operator/mig-faker
    tag: 0.0.59
statusExporter:
  image:
    pullPolicy: Always
    repository: gcr.io/run-ai-staging/fake-gpu-operator/status-exporter
    tag: 0.0.59
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  topologyMaxExportInterval: 10s
statusUpdater:
  image:
    pullPolicy: Always
    repository: gcr.io/run-ai-staging/fake-gpu-operator/status-updater
    tag: 0.0.59
  resources:
    limits:
      cpu: 400m
      memory: 400Mi
    requests:
      cpu: 200m
      memory: 200Mi
topology:
  migStrategy: mixed
  nodePoolLabelKey: run.ai/simulated-gpu-node-pool
  nodePools:
    default:
      gpuCount: 4
      gpuMemory: 22882
      gpuProduct: Tesla-K80
topologyServer:
  image:
    pullPolicy: Always
    repository: gcr.io/run-ai-staging/fake-gpu-operator/topology-server
    tag: 0.0.59
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
